### PR TITLE
Dev chlorine benoit

### LINKED ISSUE #8: Sensor must analyze all the project tree
### Expected behavior
When analyzing a project, sensor must browse all files in sub-folders.

### Actual behavior
Files in subfolders are ignored.

### Detection version
* Plugin version: V1
* SonarQube version: 6.7.4

### LINKED ISSUE #10: Display custom metrics is broken
### Expected behavior
Metrics should be displayed in standart SonarQube metrics.

### Actual behavior
There is a bad custom metrics view.

### Steps to reproduce behavior
Look at the view.

### Detection version
* Plugin version: V1
* SonarQube version: 6.7.4

### LINKED ISSUE #11: One result file can provide data about multiple source file
### Expected behavior
A Frama-C result file is abble to provide information about multiple source file. This kind of file should be importable.

### Actual behavior
Results with data about multiple source file is not importable.

### Steps to reproduce behavior
Try the plugin on this kind of result.

### Detection version
* Plugin version: V1
* SonarQube version: 6.7.4

### LINKED ISSUE #12: Source and result file names must be independant
### Expected behavior
The Frama-C result file must be named and placed independently from analyzed source files.

### Actual behavior
Currently, the result file must be named like the analyzed source file (+ result file extension) and the result folder must be place at the same tree-level.

### Detection version
* Plugin version: V1
* SonarQube version: 6.7.4

### LINKED ISSUE #16: Delete @author in source code
### Expected behavior
There should be no @author.

### Actual behavior
There are @author.

### Steps to reproduce behavior
Look at Java files.

### Detection version
1.0.0

### LINKED ISSUE #17: Normalize Built-In Quality Profile
### Expected behavior
The Built-In quality profile should contains rules and should be named Sonar way.

### Actual behavior
The way use to declare the built-in quality profile is not correct. The good class is not used and it has a non common name.

### Detection version
1.0.0

### LINKED ISSUE #18: Add a README
### Expected behavior
There should be a consistent README.

### Actual behavior
There is no real README.

### Detection version
1.0.0

### LINKED ISSUE #19: Delete useless log
### Expected behavior
There shouldn't be too much log.

### Actual behavior
There are too much log in sonar-scanner execution trace.

### Detection version
1.0.0

### LINKED ISSUE #21: Autolaunch Frama-C
### Expected behavior
User should be able to choose to autolaunch Frama-C on analysis.

### Actual behavior
User has to run Frama-C by himself before using sonar framac.

### Detection version
1.0.0

### PR DESCRIPTION
**Pull request by begarco**
### Fixes 
- Fix #8
- Fix #10
- Fix #11
- Fix #12
- Fix #16
- Fix #17
- Fix #18
- Fix #19
- Fix #21

### CODE REVIEW

File: src/main/java/fr/cnes/sonarqube/plugins/framac/rules/FramaCRulesDefinition.java [hunk 1]
```diff
@@ -1,41 +1,35 @@
...
+ * Define specific Frama-C definedRules from a given resource file: { @link
  * FramaCRulesDefinition#PATH_TO_RULES_XML }
- * 
- * @author Cyrille FRANCOIS
- *
  */
 public class FramaCRulesDefinition implements RulesDefinition {
 
-	public static final String PATH_TO_RULES_XML = "/default/framac-rules.xml";
+	public static final String PATH_TO_RULES_XML = "/rules/framac-rules.xml";
```
Comment (begarco) [inline src/main/java/fr/cnes/sonarqube/plugins/framac/rules/FramaCRulesDefinition.java]: Code Smell Code Smell: Refactor your code to get this URI from a customizable parameter. ([squid:S1075](https://sonarcloud.io/organizations/lequal/rules#rule_key=squid%3AS1075))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=fr.cnes.sonarqube.plugins%3Asonar-frama-c-plugin&pullRequest=20&issues=AWXJbamWashydt7kyasA&open=AWXJbamWashydt7kyasA)

[ISSUE_KEY]: AWXJbamWashydt7kyasA

File: src/main/java/fr/cnes/sonarqube/plugins/framac/sensor/FramaCSensor.java [hunk 2]
```diff
@@ -0,0 +1,283 @@
...
+    private List<FramaCError> analyseReportCsv(
+            final SensorContext context,
+            final String resultFile) {
+
+        List<FramaCError> errors = null;
+
+        try {
+            if (null != resultFile) {
+                final Path path = Paths.get(resultFile);
+                try (FileChannel reportFile = FileChannel.open(path)) {
```
Comment (begarco) [inline src/main/java/fr/cnes/sonarqube/plugins/framac/sensor/FramaCSensor.java]: Code Smell Code Smell: Extract this nested try block into a separate method. ([squid:S1141](https://sonarcloud.io/organizations/lequal/rules#rule_key=squid%3AS1141))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=fr.cnes.sonarqube.plugins%3Asonar-frama-c-plugin&pullRequest=20&issues=AWXs1bJoxJR_uy9B9CnS&open=AWXs1bJoxJR_uy9B9CnS)

[ISSUE_KEY]: AWXs1bJoxJR_uy9B9CnS

File: src/main/java/fr/cnes/sonarqube/plugins/framac/report/FramaCReportReader.java [hunk 3]
```diff
@@ -1,60 +1,47 @@
...
 import java.nio.charset.Charset;
 import java.nio.charset.StandardCharsets;
 import java.nio.file.Path;
-import java.util.ArrayList;
-import java.util.HashMap;
-import java.util.List;
-import java.util.Map;
-import java.util.Scanner;
+import java.util.*;
 import java.util.regex.Matcher;
```
Comment (begarco) [inline src/main/java/fr/cnes/sonarqube/plugins/framac/report/FramaCReportReader.java]: Code Smell Code Smell: Remove this unused import 'java.util.regex.Matcher'. ([squid:UselessImportCheck](https://sonarcloud.io/organizations/lequal/rules#rule_key=squid%3AUselessImportCheck))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=fr.cnes.sonarqube.plugins%3Asonar-frama-c-plugin&pullRequest=20&issues=AWXs6h8DxJR_uy9B9X4r&open=AWXs6h8DxJR_uy9B9X4r)

[ISSUE_KEY]: AWXs6h8DxJR_uy9B9X4r

File: src/main/java/fr/cnes/sonarqube/plugins/framac/sensor/FramaCSensor.java [hunk 4]
```diff
@@ -0,0 +1,277 @@
...
+        LOGGER.info("Running Frama-C and generating results to "+ outputPath);
+        try {
+            final Process framac =  Runtime.getRuntime().exec(command);
+            int success = framac.waitFor();
+            if(0!=success){
+                final String message = String.format("Frama-C auto-launch analysis failed with exit code %d.",success);
+                throw new FramaCException(message);
+            }
+            LOGGER.info("Auto-launch successfully executed Frama-C.");
+        } catch (InterruptedException | IOException | FramaCException e) {
```
Comment (begarco) [inline src/main/java/fr/cnes/sonarqube/plugins/framac/sensor/FramaCSensor.java]: Bug Bug: Either re-interrupt this method or rethrow the "InterruptedException". ([squid:S2142](https://sonarcloud.io/organizations/lequal/rules#rule_key=squid%3AS2142))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=fr.cnes.sonarqube.plugins%3Asonar-frama-c-plugin&pullRequest=20&issues=AWXs1bJoxJR_uy9B9CnU&open=AWXs1bJoxJR_uy9B9CnU)

[ISSUE_KEY]: AWXs1bJoxJR_uy9B9CnU

File: src/main/java/fr/cnes/sonarqube/plugins/framac/rules/FramaCRulesDefinition.java (hunk 1 above)
Comment (begarco) [inline src/main/java/fr/cnes/sonarqube/plugins/framac/rules/FramaCRulesDefinition.java]: Code Smell Code Smell: Refactor your code to get this URI from a customizable parameter. ([squid:S1075](https://sonarcloud.io/organizations/lequal/rules#rule_key=squid%3AS1075))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=fr.cnes.sonarqube.plugins%3Asonar-frama-c-plugin&pullRequest=20&issues=AWXJbamWashydt7kyasA&open=AWXJbamWashydt7kyasA)

[ISSUE_KEY]: AWXJbamWashydt7kyasA
